version: 2.1
jobs:
    run_tests:
        docker:
            image: circleci/node:12
        steps:
            clone:
            run:
                name: Install dependencies
                command: |
                    yarn 
                    yarn test
            store_test_results:
                path: test_results
            store_test_artifacts:
                path: test_results
workflows:
    build_test:
        jobs:
            - run_tests